First draft of a short article pushing away from using `can_connect()`
tonyandrewmeyer/misc pull request #1
Opened 2024-02-07 09:56 UTC by tonyandrewmeyer

When happy with this, it would presumably go to discourse.charmhub.io.

Also when happy with the general approach, the same types of code can be used in the tutorials, etc.

2024-02-07 09:57 UTC, tonyandrewmeyer commented
@benhoyt do you have access to review here? I can add you if not. This is still a draft, but thoughts on it so far would be great if you have some time.

2024-02-07 19:55 UTC, benhoyt commented
@tonyandrewmeyer Looks like I do have access to review here -- thanks. I'll try to take a look today.

2024-02-08 00:48 UTC, benhoyt requested changes
I originally started reviewing this as if it was going somewhere under https://juju.is/docs/sdk, but then I re-read the PR description and realised it was intended for Discourse, where the less formal style makes a lot more sense. So take some of my comments in that vein.

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +There are a few types of errors that can occur while a Charm is handling an event that are expected to resolve within a fairly short timeframe without human intervention, and can occur at any point d
This is a bit hard to parse. It sounds like the *event* is expected to resolve, but I think that's referring to the *errors*. Can you restructure/simplify/split up this sentence?

Also, nit: Charm -> charm

```suggestion
There are a few types of errors that can occur while a charm is handling an event that are expected to resolve within a fairly short timeframe without human intervention, and can occur at any point during the event handling, despite Juju's efforts to provide a stable snapshot of the model state.
```

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +    event.defer()
I'm afraid that people might read up to here and copy and paste this pattern. :-) Can we have a red "not like this" warning or at least a `# DON'T DO THIS -- SEE BELOW` type of comment?

Update: I see after reading further you're telling a story, and that's good. But I still think it'll be too easy for people to not read (people, myself included, do a lot of not-reading) and think this, or the next code snippet, is what you're suggesting... thoughts?

Also, probably better to restructure as `if not container.can_connect()` with an early return, keeping the `container.replan()` at the happy-path nesting level, as I think we/charmers would normally write it.

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +A problem with this approach is that `can_connect()` doesn't guarantee that Pebble will be reachable the next time the charm tries to communicate with it - just that it was at that point in time. Thi
```suggestion
A problem with this approach is that `can_connect()` doesn't guarantee that Pebble will be reachable the next time the charm tries to communicate with it - just that it was at that point in time. This means that we've introduced a race condition where the `can_connect()` can succeed but the `replan()` fails, and we again end up in an error state. Let's try to fix that:
```

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +However, it's clear now that the `can_connect()` call isn't doing anything useful - it's pinging Pebble but most of the time we expect Pebble will be available (so it's not required) and when it's no
```suggestion
However, it's clear now that the `can_connect()` call isn't doing anything useful - it's pinging Pebble but most of the time we expect Pebble will be available (so it's not required) and when it's not we already have the `try`/`except` to handle that. Let's make an attempt to simplify the code:
```

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +    else:
I think it's clearer/simpler to remove the `else: break` (especially with the `else` below) and just put a `break` after the `container.replan()` line.

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +        time.sleep(PEBBLE_RETRY_DELAY ** attempt)
This is a nice trick, but a little odd if `PEBBLE_RETRY_DELAY` is less than 1, say 0.5 (seconds). Then it'll go 1.0, 0.5, 0.25, etc.

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +    raise SystemExit(1)
Would this be better as `raise Exception("Unable to reach Pebble after X seconds")`?

2024-02-08 00:48 UTC, benhoyt commented on charm_temp_errors.md
> +.. TODO: I don't love how this is. A decorator or context manager is likely best. Maybe the handling of defer, return etc is too much? A class with a __getattr__ could make the call look much more li
Yeah, I'm not sure I love the `tolerant_pebble` proposal either. It seems to do too much in one tool, really two separate things: the retrying of the Pebble call, and the handling of an error. Might be worth a quick voice discussion to brainstorm whether we want this or how it should look.

2024-02-21 07:54 UTC, tonyandrewmeyer commented on charm_temp_errors.md
> +    event.defer()
> I'm afraid that people might read up to here and copy and paste this pattern. :-) Can we have a red "not like this" warning or at least a `# DON'T DO THIS -- SEE BELOW` type of comment?
> 
> Update: I see after reading further you're telling a story, and that's good. But I still think it'll be too easy for people to not read (people, myself included, do a lot of not-reading) and think this, or the next code snippet, is what you're suggesting... thoughts?

Agreed. I've put one in above, but I suspect it's not going to properly render in Discourse (I don't think Commonmark or Discourse have any built-in support for admonition blocks - you can do bbcode blocks but then you have to have custom styles so the theme really needs to support it). I'll adjust to whatever looks reasonable when actually posting.

> Also, probably better to restructure as `if not container.can_connect()` with an early return, keeping the `container.replan()` at the happy-path nesting level, as I think we/charmers would normally write it.

Yes, good call - done.

2024-02-21 23:01 UTC, benhoyt approved these changes
Couple of minor suggestions, but I'm pretty happy with this for a discourse post -- thanks!

2024-02-21 23:01 UTC, benhoyt commented on charm_temp_errors.md
> +    event.defer()
This looks good. However, if it doesn't render on Discourse, maybe we can just keep it simple with bold or something: **Warning: don't use this code ...**

2024-02-21 23:01 UTC, benhoyt commented on charm_temp_errors.md
> +    raise RuntimeError("Unable to reach Pebble")
With this approach we lose the original exception. Could we instead re-raise the exception, or at least include the original exception, in the final one?

```python
for attempt in range(MAX_PEBBLE_RETRIES):
    try:
        container.replan()
        break
    except ops.pebble.ConnectionError:
        if attempt == MAX_PEBBLE_RETRIES - 1:
            raise
        time.sleep(PEBBLE_RETRY_DELAY * attempt)
```

2024-02-23 03:29 UTC, tonyandrewmeyer commented on charm_temp_errors.md
> +    raise RuntimeError("Unable to reach Pebble")
```suggestion
for attempt in range(MAX_PEBBLE_RETRIES):
    try:
        container.replan()
        break
    except ops.pebble.ConnectionError:
        if attempt >= MAX_PEBBLE_RETRIES - 1:
            raise
        time.sleep(PEBBLE_RETRY_DELAY * attempt)
```

2024-03-01 01:25 UTC, merged